name: Main branch Gradle build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: test Detekt
      run: ./gradlew detekt
    - name: test Ktlint
      run: ./gradlew ktlintCheck

    - name: send to Slack
      uses: 8398a7/action-slack@v3 
      with:
        status: ${{ job.status }} 
        fields: job,commit,repo,author,took
        author_name: Heeg   
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 
      if: always()
